"""
User and credit-purchase service layer.

All functions are async and accept an `AsyncSession` injected by FastAPI's
`get_db` dependency.
"""
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from models import User, CreditPurchase


# ── User helpers ───────────────────────────────────────────────────────────────

async def get_user_by_email(db: AsyncSession, email: str) -> User | None:
    result = await db.execute(select(User).where(User.email == email))
    return result.scalar_one_or_none()


async def get_user_by_api_key(db: AsyncSession, api_key: str) -> User | None:
    result = await db.execute(select(User).where(User.api_key == api_key))
    return result.scalar_one_or_none()


async def create_user(db: AsyncSession, email: str) -> User:
    """
    Create a new user.  The api_key is auto-generated by the model default
    (``"tca_" + secrets.token_hex(24)``).  100 starter credits are also
    applied by the model default.
    """
    user = User(email=email)
    db.add(user)
    await db.commit()
    await db.refresh(user)
    return user


async def add_credits(db: AsyncSession, user_id: str, credits: int) -> User:
    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one()
    user.credits += credits
    await db.commit()
    await db.refresh(user)
    return user


async def deduct_credits(db: AsyncSession, user_id: str, credits: int) -> bool:
    """Deduct credits.  Returns ``False`` if the user has insufficient balance."""
    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()
    if user is None or user.credits < credits:
        return False
    user.credits -= credits
    await db.commit()
    return True


# ── Credit-purchase helpers ────────────────────────────────────────────────────

async def create_credit_purchase(
    db: AsyncSession,
    user_id: str,
    stripe_session_id: str,
    credits: int,
    amount_cents: int,
) -> CreditPurchase:
    purchase = CreditPurchase(
        user_id=user_id,
        stripe_session_id=stripe_session_id,
        credits_added=credits,
        amount_cents=amount_cents,
        status="pending",
    )
    db.add(purchase)
    await db.commit()
    await db.refresh(purchase)
    return purchase


async def complete_credit_purchase(
    db: AsyncSession,
    stripe_session_id: str,
) -> CreditPurchase | None:
    """
    Mark a purchase as completed and credit the user.
    Idempotent — safe to call multiple times for the same session.
    Returns ``None`` if the stripe_session_id is unknown.
    """
    result = await db.execute(
        select(CreditPurchase).where(
            CreditPurchase.stripe_session_id == stripe_session_id
        )
    )
    purchase = result.scalar_one_or_none()
    if purchase is None:
        return None
    if purchase.status == "completed":
        # Already processed — return without touching credits again.
        return purchase

    purchase.status = "completed"
    await db.flush()

    # Credit the user
    await add_credits(db, purchase.user_id, purchase.credits_added)

    await db.commit()
    await db.refresh(purchase)
    return purchase
